### ISSUE TITLE
US-3-crea-vista-ver-artista

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#14]
## Tasks

- [x] crea vista html con tailwing css del perfil del artista que visitara el usuario guest  (usa imagenes's de tu artista de tu gusto)
- [x] la vista debe ser responsiva con telefonos celulares
- [x] comentar un screenshot del resultado para poder hacer un review de la vista
- [ ] si el review es positivo crear una rama a partir de dev, crea una vista blade.php y una ruta ejemplo: "/artista/"
- [ ] quitar imágenes para que después sean remplazadas por bases de datos/ servidor 
- [ ] ( meet para comentar sobre imagenes mockups )

**Comment by AngelDabnee** [comment]
Página de artista terminada. 
![Captura de pantalla 2024-02-17 a la(s) 9 13 39 p m  (2)](https://github.com/REUBATCODE/leify/assets/114833669/cad5b333-49ff-424f-b833-ce07c6edd7e3)

**Comment by ivanchenoweth** [comment]
Sugiero colocar el PR ... coloquen al menos un revisor.
Protejan la rama main que solo con PR se modifique.

**Comment by REUBATCODE** [comment]
Si necesitas ayuda con esta view, me ofrezco de helper
