### ISSUE TITLE
US-4-crea-vista-ver-album

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#15]
## Tasks

- [x] crea vista html con tailwing css del album  del artista que visitara el usuario guest  (usa imagenes's de tu album de tu gusto)
- [x] la vista debe ser responsiva con telefonos celulares
- [x] comentar un screenshot del resultado para poder hacer un review de la vista o hacer un meet
- [x] quitar imágenes para que después sean remplazadas por bases de datos/ servido, si son url dejenlas luego se remplazan
- [x] DFD

**Comment by JEstebanSanti** [comment]
### asi me queddo 
![Captura de pantalla 2024-02-28 - 15 03 45](https://github.com/REUBATCODE/leify/assets/78988823/e377fad2-dbbb-4396-915e-6b8f780dc607)
### Pasa celular 

![Captura de pantalla 2024-02-28 - 15 02 57 (Pequeño)](https://github.com/REUBATCODE/leify/assets/78988823/2ef09822-68df-4fac-a5a2-1a374415f9f6)
![Captura de pantalla 2024-02-28 - 15 05 32 (Pequeño)](https://github.com/REUBATCODE/leify/assets/78988823/52b8c3d8-c78d-407c-a7b5-86462c0c7e6d)

**Comment by ivanchenoweth** [comment]
coloquen el PR correpondiente en el Develop
