### ISSUE TITLE
US-1-EPIC-GUEST

### ISSUE THREAD

**Issue by AngelDabnee** [REUBATCODE/leify#2]
# ACTIVIDADES
- [x] #3
- [x] US-1-task-vista-ver-ALBUM/mockup
- [x] US-1-task-vista-explorar/mockup
- [x] US-1-task-vista-ver-artista/mockup
- [x] US-1-task-registro

**Comment by AngelDabnee** [comment]
Mockup

[White and Grey Minimalist Headphone Store Desktop Prototype.pdf](https://github.com/REUBATCODE/leify/files/14202762/White.and.Grey.Minimalist.Headphone.Store.Desktop.Prototype.pdf)

**Comment by ivanchenoweth** [comment]
Sugiero agregar un milestone

**Comment by AngelDabnee** [comment]
Todos los mockups, no se realizó issue, debido a que se realizaron todos de "golpe", están archivados en https://drive.google.com/drive/u/0/folders/1KJlb9iikpE51fsxZ9xYWrEZwHaNOHFEa

**Comment by AngelDabnee** [comment]
Se pudo realizar el registro de un usuario GUEST con éxito. 
<img width="1440" alt="Captura de pantalla 2024-02-17 a la(s) 10 12 28 a m" src="https://github.com/REUBATCODE/leify/assets/114833669/b4b0cd46-39b6-4bc9-9463-d3ee6737ec26">
