### ISSUE TITLE
EPIC-ADMIN

### ISSUE THREAD

**Issue by AngelDabnee** [REUBATCODE/leify#21]
- [ ] US-5-DASHBOARD
- [ ] US-6-REGISTRAR-USUARIO
- [ ] US-7-ELIMINAR-USUARIO
- [ ] US-8-REGISTRAR-ARTISTA
- [ ] US-9-ELIMINAR-ARTISTA
- [ ] US-10-REGISTRAR-ALBUM
- [ ] US-11-ELIMINAR-ALBUM
- [ ] US-12-REGISTRAR-CANCION
- [ ] US-13-ELIMINAR-CANCION
