### ISSUE TITLE
US-1-crea-vista-landing-page

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#3]
## Tasks

- [x] crear un mockup y documentarlo en #3 
- [x] el mock up debe ser aprovado por almenos 1 compañero de equipo
- [ ] crear una rama con la nomenclatura decidida en #1  ver Flujo de trabajo git y versionamiento
- [ ] crear una html blade de pagina de bienvenida siguiendo el mockup
- [ ] la pagina debe ser responsiva para telefonos celulares

**Comment by ivanchenoweth** [comment]
No hay mockup?

**Comment by ivanchenoweth** [comment]
Que se va a hacer aqui?, que tareas tiene?

**Comment by AngelDabnee** [comment]
Mockup
@JEstebanSanti
@REUBATCODE

[White and Grey Minimalist Headphone Store Desktop Prototype.pdf](https://github.com/REUBATCODE/leify/files/14202762/White.and.Grey.Minimalist.Headphone.Store.Desktop.Prototype.pdf)

estos son los mockups, solo que estaban en el otro issue. se cerrará este debido a que esta duplicado

**Comment by REUBATCODE** [comment]
Landing page terminada, toca convertir el navbar y el footer en componentes.

![Image](https://github.com/REUBATCODE/leify/assets/126991341/f7dc85ac-cc35-4b4d-bbf2-f8d2c2d32f2c)



![Image](https://github.com/REUBATCODE/leify/assets/126991341/4f8049d1-cd1e-4c25-8eb8-f81fb2dabe01)



![Image](https://github.com/REUBATCODE/leify/assets/126991341/a53a768e-dd4b-4b1b-b92d-49a5544b1030)

**Comment by ivanchenoweth** [comment]
ok
