### ISSUE TITLE
US-57 busca y muestra todos albums

### ISSUE THREAD

**Issue by JEstebanSanti** [REUBATCODE/leify#49]
### Descripción
Crea una funcionalidad en la cual el el usuario guest, usuario registrado, pueda ingresar a una pagina donde se mostraran todos los albums existentes en la base de datos

### Tareas

- [ ] crea una vista donde se mostraran todos los álbumes
- [ ] crea o modifica el controlador de albumes para obtener todos los albumes
- [ ] modifica la vista para que muestre los datos obtenidos
